### ISSUE TITLE
app vs pacackage

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#232]
In the intro vignette do we need to go through and specify areas where we are referring to the package, areas where we refer to the app, and areas that are pertinent to both. @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
I would not. The package is the main deal. We should expect that our app holds the users hand enough that they eventually use package as intended (ie through R). Since there's nothing in the app that isn't just as easy in R, I would not consider bringing up the app in the intro.

**Comment by srcorsi-USGS** [comment]
OK, I am adding a note to that effect in the initial paragraphs and referring to the app vignette.
