### ISSUE TITLE
Clarification on display for single site boxplots

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#236]
For the plot_tox_boxplots function description in the workflow vignette single site example, it states:
"The difference in the output is that instead of listing the number of sites, it lists the number of unique chemical/endpoint combinations ".  Is it really the numbero of chemica/endpoint combos or just the number of chemicals that have corresponding endpoints with hit calls and with detections? @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
oh yeah, I changed the graph at some point to just chemicals....so that documentation is wrong.

**Comment by srcorsi-USGS** [comment]
Fixed
