### ISSUE TITLE
Shiny app R code

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#238]
I am adding an "R Code" section to the Shiny app vignette to describe the cut and paste process and will include the clipping code needed to make the display pretty. @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
OK, I'll remove that clipping code right now.

**Comment by ldecicco-USGS** [comment]
OK, you can do an upstream pull to get the updated app code. Or, you can install_github. I left your PR open, so any changes you make will keep getting pushed up.
