### ISSUE TITLE
Review questions

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#239]
I recommend leaving the vignettes alone until I am done with this review (today). I will go through the function doc after that. Do you have any formal (or informal) documentation that describes all of the review requirements? I just want to be certain that Dalma is the right person for the review. I don't think she is an R programmer, so may not be appropriate for vignettes other than the shinyapp one. Some documentation on the review requirements would help me decide on the right person for this. @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
1 review to assure the quality of the code (I'll get someone in data science) (ie.. from a technical expert)
and
1 review that the code produces results that are consistent with good science (ie...from a domain expert)

**Comment by srcorsi-USGS** [comment]
So, we probably need someone who uses R to do the domain expert review since a good portion of the review is outside of the app. I will talk to her and see. 
So, is there documentation that you can point me to for review requirements for my reference?
