### ISSUE TITLE
special characters in function and data documentation

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#241]
Does the same method work for adding in special characters to documentation of functions and data as it does for vignettes? e.g. ug/L would be $\mu$g/L? My first attempt in the ACC documentation did not work when I tried the "preview" option. It just used displayed as $\mu$g/L. @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
I think I've got it all now:
```
\eqn{\mu}g/L
```
that's for the roxygen. the ` $\mu$g/L` only works in the vignette

**Comment by srcorsi-USGS** [comment]
Looked extensively, found a few special characters issues in a couple functions and one vignette. fixed them, and we should be good with that now.
