### ISSUE TITLE
"User Guide"

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#249]
In a couple places, you have referred to "then vignette 'User Guide'", but there is no vignette titled User Guide. Is this just a common way to refer to the vignettes collectively or should be be more specific and refer directly to the vignette of interest?

**Comment by srcorsi-USGS** [comment]
I have changed a couple of them to point directly to the Data preparation and Shiny app vignettes. We can change them back if you would rather point to the collective vignettes

**Comment by ldecicco-USGS** [comment]
Originally, the title of the single vignette was "User Guide"...but then we split it up, so yeah, we should change those references to the ones that make sense

**Comment by srcorsi-USGS** [comment]
OK, I will try to catch them as I go through, but maybe you should keep it on the list to do a global search when I am done.
