### ISSUE TITLE
plot_ND options

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#254]
For the description of the parameter plot_ND in the plot_group_boxplots.R script, we have this:

#' @param plot_ND Logical whether or not to plot the instances when a chemical
#' was not detected. 

What does it actually use if plot_ND = TRUE. We can't give it a zero since we are using log scale. Is the concentration then set to the detection level, or what method is used?

**Comment by ldecicco-USGS** [comment]
There are 0 sites with detections, and no data plotted:

![image](https://user-images.githubusercontent.com/1105215/39769606-3fb94bae-52b2-11e8-9cb3-bb4cd9b036d8.png)

if you would make plot_ND false there:

![image](https://user-images.githubusercontent.com/1105215/39769635-5c6a4898-52b2-11e8-806c-8f4c658b1068.png)

In the OWC data, there's not a big difference...but some of the other data sets have a ton of chemicals that are never detected.

**Comment by srcorsi-USGS** [comment]
OK, I am misinterpreting the utility of that parameter. I thought it was going to be plotting all sites in the boxplot rather than only the ones with detections (57 data points for all boxplots). This makes more sense.
