### ISSUE TITLE
Basic Workflow vignette snafu

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#261]
In the "Maps" section, the map does not render at all. I see the data points, but no more.

**Comment by srcorsi-USGS** [comment]
In RStudio clicking through the help package to the vignette.

**Comment by srcorsi-USGS** [comment]
Within the RStudio window:
![image](https://user-images.githubusercontent.com/1444781/39779608-588ef33c-52cf-11e8-90f8-d9e704a77134.png)

**Comment by ldecicco-USGS** [comment]
The background does need an internet connection, so maybe it just didn't load right for you. Works for me though. Maybe click the refresh button?:

![image](https://user-images.githubusercontent.com/1105215/39779834-f2f2db64-52cf-11e8-84da-184e1bbf1742.png)

It might depend how you installed it most recently. For good measure, you could do another:
```
devtools::install_github("USGS-R/toxEval")
```

**Comment by srcorsi-USGS** [comment]
I just reinstalled from github and re-checked this on my laptop and on my desktop. The laptop works fine. The desktop still has this problem. As far as I can tell, the R version and the toxEval version are the same for the two machines.

**Comment by ldecicco-USGS** [comment]
I'm going to close this because the main work of this function is to plot the points in a lat/lon coordinate system. We have very little control of the basemaps showing up or not.
