### ISSUE TITLE
Suggested changes to toxEval vignettes

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/toxEval#268]
The vignettes look great and give a good overview to the process/data/package. Below are some suggestions to improve the flow and interpretability for the user -- take them or leave them! 

**Introduction vignette:**

- include the column names and definitions within the help file for ?endPointInfo in case that PDF from EPA moves or goes away?
- ~~define “intended_target_family” in the Grouping Options section~~

**Preparing data:**
- ~~what to do with values BDL? This seems like it should be stated in the "preparing data" section.~~
- An example for classes? ~~Also, I think Laura showed me a way to automatically generate the chemicals tab of the spreadsheet, shouldn't we show that in the "preparing data" vignette to save users the trouble?~~ [I think we've changed the "Chemical" requirements since this review that it is no longer as painful as it was, ie, you don't need molecular weights] 
- In the exclude section of "preparing data" - why not just use our example of why to exclude a certain endpoint? e.g., that we lacked confidence in the dose-response curve? This seems like a good bit of info to pass along, adn is currently vague with "not an appropriate endpoint"
- ~~The "endPoint" in benchmarks seems really confusing - especially since endPoints is used in the context of toxcast. Also, the endpoint is the thing that is measured in toxcast, where as the example seems more like the type of chemical exposure from which the benchmark was determined. could you just call this "benchmark"?~~ [Moved to #281 ]

**Basic workflow:**
- ~~I don't understand what's going on in clean_endpoint_info section, specifically what "removal of endPoints that are ATG sources with signal loss and NVS with signal gain" means.~~ 

- ~~Seems like the "custom configuration" section could be moved down into the context of visualization.~~

- ~~plot_tox_boxplot: Describe what the "extra" ggplot steps are doing - this is unclear, especially if this is part of ggplot or the package?  Okay - now see this has its own section - maybe add this as a subsection the first time its used in a visualization?~~
- ~~One common way to order data would be from lowest to highest EAR (total, not grouped by anything). Maybe show this as an additional example, both how to get that data and how to use it to order factors? This seems like it can be achieved in the tables section.~~ (See #268) 
- ~~In tables, I find this statement slightly awkward/confusing at first: "The tables show slightly different results for a single site". What about, "You can also create tables that summarize individual sites, where the number of samples with hits is presented."~~

**Comment by ldecicco-USGS** [comment]
I'm adding strikethroughs to bullets that I think I've addressed. 

The idea to re-order the boxplots to not take into account chemcial classes sounds good...but a bit much work for now. I'll add an Issue as an enhancement for a later date.

**Comment by ldecicco-USGS** [comment]
OK, I added new issues where I thought we could still consider work. I addressed the rest (in my opinion). @limnoliver feel free to re-open this issue if you think the changes lately weren't enough!
