### ISSUE TITLE
Benchmark rewrite?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/toxEval#281]
From #268 
```
The "endPoint" in benchmarks seems really confusing - especially since endPoints is used in the context of toxcast. Also, the endpoint is the thing that is measured in toxcast, where as the example seems more like the type of chemical exposure from which the benchmark was determined. could you just call this "benchmark"?
```

Hmm...I struggle to figure out which would be better in the "Benchmark" tab. First off...we don't know that users will be using single benchmark values...maybe there is another data base or something that has these more nuanced "end point"-like values. Since it would be a fair amount of work to incorporate it deviating from the ToxCast format, I'm leaving it for now, but labeling this issue as an enhancement. I might play around with it in the next couple days.

**Comment by srcorsi-USGS** [comment]
Many of the "benchmarks" that could be used could also be referred to as endpoints if the user elects to use individual assay results (e.g. LC50 for fathead minnows). We have been calling them benchmarks for lack of a general term that covers all options. I don't see "endpoint" as a very limiting term. It can probably be left as is.
