### ISSUE TITLE
Missing compound

### ISSUE THREAD

**Issue by lw583** [USGS-R/toxEval#304]
Hello,

I currently have 18 compounds which can be read by ToxCast but venlafaxine appears to be missing in the output. Having double-checked the CAS numbers, I re-ran my file with ONLY venlafaxine concentrations and it resulted in no output (attached is my code with the graphed output). I have also attached a graph of venlafaxine intensity (which I input as a concentration in ug/L). Is this a bug with the package? Thanks.

```
path_to_file <- "venlafaxine.xlsx"
tox_list <- create_toxEval(path_to_file)

ACC <- get_ACC(tox_list$chem_info$CAS)
ACC <- remove_flags(ACC)

cleaned_ep <- clean_endPoint_info(end_point_info)
filtered_ep <- filter_groups(cleaned_ep)

chemical_summary <- get_chemical_summary(tox_list, ACC, 
                                         filtered_ep)

chemical <- chemical_summary$chnm
date <- as.factor(chemical_summary$date)
EAR <- chemical_summary$EAR

ggplot(data=data.frame(EAR), aes(as.Date(date)))+
  geom_line(aes(y=EAR))+
  xlab("Date")+
  ylab("EAR")
```

<img width="503" alt="screenshot 2019-03-06 at 12 29 44 pm" src="https://user-images.githubusercontent.com/46941988/53990620-aec83680-40f6-11e9-9ee4-c7d99dabaab1.png">
<img width="797" alt="screenshot 2019-03-07 at 4 36 29 pm" src="https://user-images.githubusercontent.com/46941988/53990834-2e560580-40f7-11e9-810e-3d54550c6c7e.png">

**Comment by ldecicco-USGS** [comment]
It looks like the only information on venlafaxine is from the assay "TOX21_p53_BLA_p4_ch2". When you run the `filter_groups` function, it looks like you remove that assay because it is considered a "Background Measurement" in the "intended_target_family".
