### ISSUE TITLE
Pivot article revisions

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#358]
A few things that could be explained in the pivot article:

line 55: the "names_to" vector should be explained a little. What exactly to the values in the vector represent?
The same with the names_pattern vector. What does "(.+)_(.+)" represent?

names_to = c("Chemical", ".value"),
               names_pattern = "(.+)_(.+)")

**Comment by ldecicco-USGS** [comment]
I added some text:

http://usgs-r.github.io/toxEval/articles/pivot.html
