### ISSUE TITLE
Multiple endpoints per sample

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#58]
1. Dealing with multiple endpoints per sample
   -group by assays?
   -group by cytotoxicity
   -group by endocrine disruption.
   -xenobiotic metabolism enzymes
   -hepatic metabolizing enzymes
   -look at ToxPi groupings--make separate column for ToxPi wedges. Use published materials to choose.

compute mean, median, max, summation for each grouping. Determine how many endpoints got hit.

Duluth: determine groupings (approx 2-weeks out)
USGS: use groupings to compute summary info.

**Comment by srcorsi-USGS** [comment]
User input file (csv) that will allow the user to define groupings by column.

**Comment by ldecicco-USGS** [comment]
per sample or per site? or either

**Comment by ldecicco-USGS** [comment]
summary stats for EAR per sample (unique site/date)

**Comment by ldecicco-USGS** [comment]
let the stat be an argument

**Comment by ldecicco-USGS** [comment]
For a given site, summary stats of the summary stats (always use summation as default)

**Comment by ldecicco-USGS** [comment]
Boxplot of output

**Comment by ldecicco-USGS** [comment]
Add number of endpoints (and list them) for chosen group/groupCol

**Comment by ldecicco-USGS** [comment]
Add number of chemicals that have hits

**Comment by ldecicco-USGS** [comment]
Instead of sumHits, we want 

mean of nHits, max of nHits, and number of samples with hits
