### ISSUE TITLE
Chemical mixtures

### ISSUE THREAD

**Issue by srcorsi-USGS** [USGS-R/toxEval#59]
Dealing with chemical mixtures
  -Sum EARs within assays: e.g. one value summed for all chemicals for each endpoint.
  -route these results into the multiple endpoints routine (look at groupings of endpoints that make sense to sum the EARs for total effect--e.g. groups that work on the same mode of action).

**Comment by ldecicco-USGS** [comment]
Capture what chemicals are returned from our groupings.

Boxplots
